import { useEffect, useRef, useState } from "react";
import LiveMap from "../components/tracking/LiveMap";

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:5000/api";

const LiveTracking = () => {
  // temporary hardcoded trip id
  // later replace with useParams()

  const tripId = "6a6a6fa93ffa03ab2c63ba0b";

  const [liveData, setLiveData] = useState(null);

  const [tripData, setTripData] = useState(null);

  const [startingTrip, setStartingTrip] = useState(false);

  const [tripStarted, setTripStarted] = useState(false);

  const [tripCompleted, setTripCompleted] = useState(false);

  const [message, setMessage] = useState("");

  const intervalRef = useRef(null);

  // ---------------------------
  // Fetch Complete Trip
  // Gets route generated by OSRM
  // ---------------------------

  const fetchTrip = async () => {
    try {
      const response = await fetch(`${BASE_URL}/trips/${tripId}`);

      const data = await response.json();

      if (data.success) {
        setTripData(data.data);
      }
    } catch (error) {
      console.log("Trip fetch error:", error);
    }
  };

  // ---------------------------
  // Fetch Live Location
  // Dynamic stats source
  // ---------------------------

  const fetchLiveData = async () => {
    try {
      const response = await fetch(`${BASE_URL}/trips/live/${tripId}`);

      const data = await response.json();

      if (data.success) {
        setLiveData(data.data);

        if (data.data.status === "Completed") {
          stopPolling();

          setTripCompleted(true);

          setTripStarted(false);

          setMessage("🎉 Trip Completed Successfully!");
        }
      }
    } catch (error) {
      console.log("Live tracking error:", error);

      stopPolling();
    }
  };

  // ---------------------------
  // Stop polling
  // ---------------------------

  const stopPolling = () => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);

      intervalRef.current = null;
    }
  };

  // ---------------------------
  // Start Trip
  // ---------------------------

  const handleStartTrip = async () => {
    try {
      setStartingTrip(true);

      const response = await fetch(
        `${BASE_URL}/trips/start/${tripId}`,

        {
          method: "POST",

          headers: {
            "Content-Type": "application/json",
          },
        },
      );

      const data = await response.json();

      if (data.success) {
        setTripStarted(true);

        setTripCompleted(false);

        fetchTrip();

        fetchLiveData();
      }
    } catch (error) {
      console.log(error);

      alert("Unable to start trip");
    } finally {
      setStartingTrip(false);
    }
  };

  // ---------------------------
  // Poll every 500ms
  // ---------------------------

  useEffect(() => {
    if (!tripStarted) return;

    stopPolling();

    intervalRef.current = setInterval(() => {
      fetchLiveData();
    }, 500);

    return () => stopPolling();
  }, [tripStarted]);

  // initial route load

  useEffect(() => {
    fetchTrip();

    fetchLiveData();
  }, []);

  // ---------------------------
  // Dynamic Stats
  // ---------------------------

  const progress = liveData?.totalPoints
    ? Math.round((liveData.currentIndex / liveData.totalPoints) * 100)
    : 0;

  const speed = liveData?.location?.speed || 0;

  const distance = liveData?.totalDistance || 0;

  const status = liveData?.status || "Ready";

  return (
    <div className="min-h-screen bg-base-200 p-6">
      <div className="max-w-7xl mx-auto">
        <div className="flex justify-between items-center mb-6">
          <div>
            <h1 className="text-4xl font-bold">🚗 Live Vehicle Tracking</h1>

            <p className="opacity-60">Trip ID : {tripId}</p>
          </div>

          <button
            className="btn btn-primary"
            disabled={startingTrip || tripStarted || tripCompleted}
            onClick={handleStartTrip}
          >
            {startingTrip
              ? "Starting..."
              : tripCompleted
                ? "Completed"
                : tripStarted
                  ? "Running"
                  : "▶ Start Trip"}
          </button>
        </div>

        {message && <div className="alert alert-success mb-5">{message}</div>}

        {/* Progress */}

        <div className="card bg-base-100 shadow mb-5">
          <div className="card-body">
            <div className="flex justify-between">
              <span>Trip Progress</span>

              <span>{progress}%</span>
            </div>

            <progress
              className="progress progress-primary w-full"
              value={progress}
              max="100"
            />
          </div>
        </div>

        <LiveMap liveData={liveData} tripData={tripData} />

        {/* Stats */}

        <div className="grid md:grid-cols-3 gap-5 mt-6">
          <div className="card bg-base-100 shadow">
            <div className="card-body">
              <h2 className="font-bold">⚡ Speed</h2>

              <p className="text-3xl">{speed} km/h</p>
            </div>
          </div>

          <div className="card bg-base-100 shadow">
            <div className="card-body">
              <h2 className="font-bold">📍 Distance</h2>

              <p className="text-3xl">{distance} km</p>
            </div>
          </div>

          <div className="card bg-base-100 shadow">
            <div className="card-body">
              <h2 className="font-bold">Status</h2>

              <div className="badge badge-primary">{status}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LiveTracking;
